DROP SCHEMA IF EXISTS CCABooking CASCADE;
CREATE SCHEMA CCABooking;
SET Search_path to CCABooking, public;

CREATE TABLE LeadCustomer 
(
	CustomerID INTEGER PRIMARY KEY NOT NULL,
	FirstName VARCHAR(20)  NOT NULL,
	Surname VARCHAR(40)  NOT NULL,
	BillingAddress VARCHAR(200)  NOT NULL,
	email  VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE Passenger 
(
	PassengerID INTEGER PRIMARY KEY NOT NULL,
	FirstName VARCHAR(20)  NOT NULL,
	Surname VARCHAR(40)  NOT NULL,
	PassportNo VARCHAR(30) NOT NULL UNIQUE,
	Nationality VARCHAR(30) NOT NULL,
	Dob DATE NOT NULL
);

CREATE TABLE Flight 
(
	FlightID INTEGER PRIMARY KEY NOT NULL,
	FlightDate TIMESTAMP NOT NULL, 
	Origin VARCHAR(30) NOT NULL,
	Destination VARCHAR(30) NOT NULL,
	MaxCapacity INTEGER NOT NULL,
	PricePerSeat DECIMAL NOT NULL
);

-- CREATE DOMAIN StatusType AS CHAR(1) DEFAULT 'R' CHECK (VALUE IN ('C', 'R'));

CREATE TABLE FlightBooking 
(
	BookingID INTEGER NOT NULL PRIMARY KEY,
	CustomerID INTEGER NOT NULL,
	FlightID INTEGER NOT NULL, 
	NumSeats INTEGER NOT NULL,
	Status CHAR(1) NOT NULL CHECK (Status in ('C', 'R')) DEFAULT 'R',
	BookingTime TIMESTAMP NOT NULL,
	TotalCost DECIMAL,
	FOREIGN KEY(CustomerID) REFERENCES LeadCustomer ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FlightID) REFERENCES Flight ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SeatBooking
(
	BookingID INTEGER NOT NULL,
	PassengerID INTEGER NOT NULL,
	SeatNumber CHAR(4) NOT NULL,
	PRIMARY KEY(BookingID, PassengerID),
	FOREIGN KEY(BookingID) REFERENCES FlightBooking ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(PassengerID) REFERENCES Passenger ON DELETE CASCADE ON UPDATE CASCADE
);
